### ISSUE TITLE
[Bug] Cannot build Android,  Could not get resource 'https://jcenter.bintray.com

### ISSUE THREAD

**Issue by retyui** [ammarahm-ed/react-native-mmkv-storage#158] opened 2021-09-16 12:25 UTC
**Describe the bug**

I've just added this module and try to build my app

but it failed with next error:

```log
A problem occurred configuring project ':react-native-mmkv-storage'.
> Could not resolve all artifacts for configuration ':react-native-mmkv-storage:classpath'.
   > Could not resolve com.android.tools.build:builder:3.4.2.
     Required by:
         project :react-native-mmkv-storage > com.android.tools.build:gradle:3.4.2
      > Could not resolve com.android.tools.build:builder:3.4.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/builder/3.4.2/builder-3.4.2.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/builder/3.4.2/builder-3.4.2.pom'.
               > Read timed out
   > Could not resolve com.android.tools.build:gradle-api:3.4.2.
     Required by:
         project :react-native-mmkv-storage > com.android.tools.build:gradle:3.4.2
         project :react-native-mmkv-storage > com.android.tools.build:gradle:3.4.2 > com.android.tools.lint:lint-gradle-api:26.4.2
      > Could not resolve com.android.tools.build:gradle-api:3.4.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle-api/3.4.2/gradle-api-3.4.2.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle-api/3.4.2/gradle-api-3.4.2.pom'.
               > Read timed out
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform Information:**
 - OS: [e.g. iOS/Android]
 - React Native Version [e.g. 0.64]
 - Library Version [e.g. 0.5.8]

**Additional context**

**Comment by retyui** [comment] 2021-09-16 12:29
Maybe it can help

https://github.com/react-native-async-storage/async-storage/blob/56d1146269ff0a3a3b7fa90ac5e2faebab09d72c/android/build.gradle#L45-L50

**Comment by ammarahm-ed** [comment] 2021-09-16 13:38
The issue is already fixed on master branch

**Comment by retyui** [comment] 2021-09-16 13:49
is it possible to release it asap?

**Comment by ammarahm-ed** [comment] 2021-09-18 14:35
Released new version on npm

**Closed as completed by ammarahm-ed** 2021-09-18 14:35 UTC
