### ISSUE TITLE
Failed to resolve: com.tencent:mmkv-static:1.2.0

### ISSUE THREAD

**Issue by hoanglam10499** [ammarahm-ed/react-native-mmkv-storage#28] opened 2020-07-06 01:28 UTC
![error](https://user-images.githubusercontent.com/37326429/86547074-e270d600-bf61-11ea-8440-6d08d533f314.png)

@ammarahm-ed 
I have issues with version 0.3.3. Change "com.tencent:mmkv-static:1.2.0" ==> "com.tencent:mmkv-static:1.1.1", it will work.

**Comment by ammarahm-ed** [comment] 2020-07-06 02:36
The issue is happening due a critical bug in MMKV 1.2.0 discovered recently by the dev. Its been updated to 1.2.1 now which is available, the older version is removed so it cannot be found. I will fix it today and push a new update.

**Comment by ammarahm-ed** [comment] 2020-07-06 04:21
Fixed in **v0.3.5**

**Closed as completed by ammarahm-ed** 2020-07-06 04:21 UTC
